services:
  ai-api:
    build: .
    container_name: ai-api
    ports:
      - "8000:8000"
    volumes:
      - ./models/Phi-4-multimodal-instruct:/models/Phi-4-multimodal-instruct
    cpus: 4.0

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OPENAI_API_KEY=sk-xxx
      - OPENAI_API_BASE_URL=http://ai-api:8000/v1
    ports:
      - "4000:8080"
    depends_on:
      - ai-api
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data:
